lim:   # 配置tcp
  tcpPort: 9001
  webSocketPort: 19001
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000   # 心跳超时时间，单位毫秒
  brokerId: 1001

  redis:    # 配置Redis
    mode: single # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 1
    password: 942633
    timeout: 3000 # 超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(毫秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 192.168.88.130:6379

  rabbitmq:  # 配置RabbitMQ
    host: 192.168.88.130
    port: 5672
    virtualHost: /
    userName: root
    password: 942633

  zkConfig:   # 配置zookeeper
    zkAddr: 127.0.0.1:2181   # zookeeper的地址
    zkConnectTimeOut: 5000   # zookeeper超时时间