lim:   # 配置tcp
  tcpPort: 9000
  webSocketPort: 19000
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000   # 心跳超时时间，单位毫秒
  brokerId: 1000
  loginModel: 1   # 多端登录的不同模式
  #  多端同步模式：1 只允许一端在线，手机/电脑/web 踢掉除了本client+imei的设备
  #               2 允许手机/电脑的一台设备 + web在线 踢掉除了本client+imei的非web端设备
  #               3 允许手机和电脑单设备 + web 同时在线 踢掉非本client+imei的同端设备
  #               4 允许所有端多设备登录 不踢任何设备
  logicUrl: http://127.0.0.1:8000/v1



  redis:    # 配置Redis
    mode: single # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 0
    password: 942633
    timeout: 3000 # 超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(毫秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 192.168.88.130:6379

  rabbitmq:  # 配置RabbitMQ
    host: 192.168.88.130
    port: 5672
    virtualHost: /
    userName: root
    password: 942633

  zkConfig:   # 配置zookeeper
    zkAddr: 127.0.0.1:2181   # zookeeper的地址
    zkConnectTimeOut: 5000   # zookeeper超时时间